name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - uses: denoland/setup-deno@main
      with:
        deno-version: "1.33.3"
    - name: Run linter
      if: matrix.os == 'ubuntu-latest'
      run: |
        deno task lint
    - name: Check mod.ts
      run: |
        deno task typecheck
    - name: Run tests
      run: |
        deno task test
    - name: Generate an lcov report
      run: |
        deno task coverage
    - uses: k1LoW/octocov-action@v0
