name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - name: Get deno version
      id: deno-version
      run: |
        echo "version=$(cat .deno-version)" >> ${GITHUB_OUTPUT}
    - uses: denoland/setup-deno@main
      with:
        deno-version: ${{ steps.deno-version.outputs.version }}
    - uses: actions/cache@v3
      with:
        path: |
          ~/.deno
          ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('**/*deps.ts', '**/.deno-version') }}
    - name: Run linter
      if: matrix.os == 'ubuntu-latest'
      run: |
        deno task lint
    - name: Check mod.ts
      run: |
        deno task typecheck
    - name: Run tests
      run: |
        deno task test
    - name: Generate an lcov report
      run: |
        deno task coverage
    - uses: k1LoW/octocov-action@v0
